project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!course_materials/templates/"

website:
  announcement:
    icon: info-circle
    dismissable: false
    position: above-navbar
    content: "Course materials are currently undergoing revision! EDS 240 will begin again in January 2026. In the meantime, things here might get a little messy {{< fa face-grin-beam-sweat >}}"
  title: "EDS 240"
  favicon: images/EDS240-hex.png
  navbar:
    right:
      - text: home
        href: index.qmd
      - text: syllabus
        href: https://docs.google.com/document/d/19Fr6XxobSM7OAdqcpZ7AyZ4qGHO5iLyS6iGEkP4W7SU/edit?usp=sharing
        target: _blank
      - text: course materials
        menu:
          - text: week 1 (1/7) - **syllabus, intro, review**
            href: course-materials/week1.qmd
          - text: week 2 (1/14)
            href: course-materials/week2.qmd
          - text: week 3 (1/21)
            href: course-materials/week3.qmd
          - text: week 4 (1/28)
            href: course-materials/week4.qmd
          - text: week 5 (2/4)
            href: course-materials/week5.qmd
          - text: week 5 (2/7) - attendance optional
            href: course-materials/graphic-design.qmd
          - text: week 6 (2/11)
            href: course-materials/week6.qmd
          - text: week 7 (2/18)
            href: course-materials/week7.qmd
          - text: week 8 (2/25)
            href: course-materials/week8.qmd
          - text: week 9 (3/4)
            href: course-materials/week9.qmd
          - text: week 10 (3/111)
            href: course-materials/week10.qmd
          - text: week 11 (3/19) - finals week
            href: course-materials/week11.qmd
      - text: assignments
        href: assignments.qmd
      - text: redeem tokens
        href: https://forms.gle/ePS4Hm4kH1PhusGX7
        target: _blank
      - text: resources
        menu:
          - text: recommended reading & materials
            href: resources.qmd
          - text: guide for writing clean code
            href: clean-code-guide.qmd
          - text: getting unstuck
            href: getting-unstuck.qmd
          - text: MEDS installation guide
            href: https://ucsb-meds.github.io/MEDS-installation-guide/
            target: _blank
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/samanthacsik/EDS-240-data-viz
            target: _blank
          - text: Report a Bug
            url:  https://github.com/samanthacsik/EDS-240-data-viz/issues
            target: _blank
  page-footer:
    background: dark
    right: This website is built with [{{< fa brands github title="the github octocat logo" >}}](https://github.com/samanthacsik/EDS-240-data-viz), [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html) and [Quarto](https://quarto.org/)
    # center: |
    #   <img src="images/bren-logo.png" alt="The Bren School of Environmental Science & Management logo" width="250"/>
    left: This course was originally developed by S. Shanny-Csik and is licensed under a [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/)

format:
  html:
    theme: meds-website-styles.scss
    title-block-banner: true
    toc: true
    code-line-numbers: true
    page-layout: full

